targetPort: 3000
deployEnv: prod
IPFS_GATEWAYS: https://ipfs.io/ipfs/,https://api.universalprofile.cloud/ipfs/
ARWEAVE_GATEWAY: https://arweave.net/
RPC_URL: http://leequid-0.leequid.org:8545
REDIS_URI: redis://redis-headless:6379/2

redis:
  enabled: true
  fullnameOverride: redis

  image:
    tag: 7.2.0-debian-11-r0

  auth:
    enabled: false

  global:
    storageClass: premium-rwo

  master:
    persistence: &redis-size
      size: 2Gi
    resources: &redis-resources
      requests:
        cpu: 50m
        memory: 256Mi
      limits:
        memory: 256Mi

  replica:
    replicaCount: 0
    persistence: *redis-size
    resources: *redis-resources

  metrics:
    enabled: true