Feature: Auth Scenarios

  Scenario: Whitelisted user Login with 2FA
    Given a user email is withelisted in the app
    When the user chooses to sign in using their Google account
    Then they should also enter a 2FA code generated by the Google Authenticator app
    And upon entering valid credentials and 2FA code
    And the system should return a valid JWT
    Then the service should return HTTP 200

