Feature: Auth Scenarios

  Scenario: User Registration and Google Sign-In
    Given a user wants to access the application
    When the user chooses to sign up using their Google account
    Then they should be redirected to the Google Sign-In page
    And they should provide their Google credentials
    And upon successful Google authentication
    Then a new user account should be created in the application
    And the user should be logged in
    And they should have to to enable 2FA


  Scenario: User Enabling Two-Factor Authentication (2FA)
    Given a user is logged into their account
    When the user enable 2FA
    Then they should be guided through the 2FA setup process
    And they should be provided with a QR code to scan with a Google Authenticator app
    And they should also receive a backup code
    And after successfully setting up 2FA
    Then their account should be 2FA-enabled
    And they should be required to enter a 2FA code during login


  Scenario: User Login with 2FA
    Given a user has 2FA enabled for their account
    When the user chooses to sign in using their Google account
    Then they should also enter a 2FA code generated by the Google Authenticator app
    And upon entering valid credentials and 2FA code
    Then the service should return HTTP 200


  Scenario: Security Measures
    Given a user is logged into their account
    When a user logs in with invalid credentials
    Then the service should return HTTP 500
    And they should receive an error message indicating invalid credentials
    And after a certain number of failed login attempts, the account should be temporarily locked
    And the user should receive a notification about the lockout


  Scenario: Account Recovery
    Given a user has forgotten their password or cannot access their 2FA device
    When the user clicks on the "Forgot Password" or "Lost 2FA Device" link
    Then they should be guided through a secure account recovery process
    And after successful recovery
    Then the user should be able to reset their password or re-enable 2FA


  Scenario: Unauthorized Access Attempt
    Given a user is logged into their account
    When an unauthorized person attempts to access the user's account
    Then the service should return HTTP 403
    And the user should receive a notification or alert about the login attempt
