apiVersion: apps/v1
kind: Deployment
metadata:
  name: indexer-admin-testnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: indexer-admin-testnet
  template:
    metadata:
      labels:
        app: indexer-admin-testnet
    spec:
      containers:
        - name: indexer-admin-testnet
          image: europe-west1-docker.pkg.dev/dropps-indexing/indexing/indexer-admin:latest
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: LUKSO_DATA_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config-testnet
                  key: LUKSO_DATA_CONNECTION_STRING
            - name: LUKSO_STRUCTURE_CONNECTION_STRING
              valueFrom:
                configMapKeyRef:
                  name: app-config-testnet
                  key: LUKSO_STRUCTURE_CONNECTION_STRING
            - name: RPC_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config-testnet
                  key: RPC_URL
            - name: IPFS_GATEWAYS
              valueFrom:
                configMapKeyRef:
                  name: app-config-testnet
                  key: IPFS_GATEWAYS
            - name: ARWEAVE_GATEWAY
              valueFrom:
                configMapKeyRef:
                  name: app-config-testnet
                  key: ARWEAVE_GATEWAY
            - name: REDIS_URI
              value: redis://redis-headless:6379