export enum REDIS_KEY {
  LATEST_TX_INDEXED_BLOCK = 'latest_tx_indexed_block',
  LATEST_EVENT_INDEXED_BLOCK = 'latest_event_indexed_block',
  LATEST_UPDATE_DATE = 'latest_update_date',
  SKIP_TX_COUNT = 'skip_tx_count',
  SKIP_EVENT_COUNT = 'skip_event_count',
  SKIP_EVENT_PARAMS_COUNT = 'skip_event_params_count',
  SKIP_CONTRACT_COUNT = 'skip_contract_count',
  DECODED_TX_COUNT = 'decoded_tx_count',
  DECODED_EVENT_COUNT = 'decoded_event_count',
  DECODED_CONTRACT_COUNT = 'decoded_contract_count',
  DECODED_ERC725Y_COUNT = 'decoded_erc725y_count',
  FAILED_DECODE_TX_COUNT = 'failed_decode_tx_count',
  FAILED_DECODE_EVENT_COUNT = 'failed_decode_event_count',
  FAILED_DECODE_CONTRACT_COUNT = 'failed_decode_contract_count',
  FAILED_DECODE_ERC725Y_COUNT = 'failed_decode_erc725y_count',
  FAILED_UNWRAP_TX_COUNT = 'failed_unwrap_tx_count',
  FETCHED_METADATA_COUNT = 'fetched_metadata_count',
  FAILED_FETCH_METADATA_COUNT = 'failed_fetch_metadata_count',
  P_LIMIT = 'p_limit',
  BLOCKS_P_LIMIT = 'blocks_p_limit',
  EVENTS_CHUNK_SIZE = 'event_chunk_size',
  BLOCK_CHUNK_SIZE = 'block_chunk_size',
}
